---
# Variables pour le réseau LXD
ipv6_address: none
network_name: "lxdbr0"
ipv4_address: "10.0.8.1/24"
ipv4_nat: "true"
# Variables pour le profil Kubernetes
k8s_profile_name: k8s-profile1
k8s_profile_config:
  limits.cpu: "2"
  limits.memory: 2GB
  limits.memory.swap: "false"
  linux.kernel_modules: ip_tables,ip6_tables,nf_nat,overlay,br_netfilter
  raw.lxc: |
    lxc.apparmor.profile=unconfined
    lxc.cap.drop=
    lxc.cgroup.devices.allow=a
    lxc.mount.auto=proc:rw sys:rw cgroup:rw
  security.nesting: "true"
  security.privileged: "true"

k8s_profile_devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: kube0
    type: nic
  kmsg:
    path: /dev/kmsg
    source: /dev/kmsg
    type: unix-char
  root:
    path: /
    pool: lxd-storage
    type: disk

pool_name: "zfspool"         # Nom du pool ZFS à créer
disk_device: "/dev/sdb"      # Périphérique à utiliser (laissez vide pour file loop)
loop_size: "20GB"


# Conteneurs à créer pour le cluster Kubernetes :
containers:
  - name: k8s-master       # Master node du cluster Kubernetes.
    image_alias: ubuntu/20.04
  - name: k8s-worker1      # Premier worker node.
    image_alias: ubuntu/20.04

