---

- hosts: all 
  become: yes 
  roles:
    - role: kubernetes-common

- hosts: masters
  become: yes       
  roles:
    - role: kubernetes-master

- hosts: workers    
  become: yes       
  roles:
    - role: kubernetes-worker