---
- name: Inclure des tâches conditionnellement
  include_tasks: join.yaml
  when: inventory_hostname is regex('^.*-worker-1$') and inventory_hostname.split('-')[0] == cluster_name


# Tâche de débogage ajoutée AVANT l'include_tasks
- name: Déboguer la condition pour
  ansible.builtin.debug:
    msg: |
      --- Débogage pour l'hôte: {{ inventory_hostname }} ---
      Valeur de 'inventory_hostname':       {{ inventory_hostname }}
      Valeur de 'cluster_name':           {{ cluster_name }}

      Partie 1: inventory_hostname correspond-il à regex('^.*-worker-1$') ?
      Résultat Regex:                     {{ inventory_hostname is regex('^.*-worker-1$') }}

      Partie 2: Le préfixe de l'hôte correspond-il à cluster_name ?
      Préfixe ('inventory_hostname.split('-')[0]'): {{ inventory_hostname.split('-')[0] }}
      Résultat Comparaison Préfixe:       {{ inventory_hostname.split('-')[0] == cluster_name }}

      Résultat final de la condition 'when': {{ (inventory_hostname is regex('^.*-worker-1$')) and (inventory_hostname.split('-')[0] == cluster_name) }}
      --- Fin du débogage ---
  #Optionnel: Condition pour éviter les erreurs si les variables ne sont pas définies
  

# - name: Afficher inventory_hostname
#   ansible.builtin.debug:
#     msg: "Le nom d'hôte de l'inventaire est : {{ inventory_hostname }}"

# - name: Afficher inventory_hostname_short
#   ansible.builtin.debug:
#     msg: "Le nom d'hôte court de l'inventaire est : {{ inventory_hostname_short }}"

# - name: Afficher ansible_hostname
#   ansible.builtin.debug:
#     msg: "Le nom d'hôte découvert (fact) est : {{ ansible_hostname }}"