
---
- name: Installation des paquets LXC et dépendances
  apt:
    name:
      - lxc
      - lxc-dev
      - python3-dev
      - python3-lxc
    state: present
    update_cache: yes

- name: Vérifier si LXD est installé via Snap
  shell: snap list | grep -q "^lxd"
  register: lxd_installed
  failed_when: false
  changed_when: false

- name: Installer LXD via Snap si non installé
  community.general.snap:
    name: lxd
    channel: 5.0/stable
  when: lxd_installed.rc != 0

- name: Initialiser LXD (si non initialisé)
  shell: |
    lxd init --auto
  args:
    creates: /var/snap/lxd/common/lxd
    
- name: Vérifier si le pool existe déjà
  shell: lxc storage list --format csv | grep "^{{ pool_name }},"
  register: pool_exists
  failed_when: false
  changed_when: false

- name: Créer le pool ZFS avec un fichier loop si aucun périphérique n'est spécifié
  command: /snap/bin/lxc storage create {{ pool_name }} zfs
  when:
    - pool_exists.rc != 0 or pool_exists.stdout == ''

- name: Vérifier si le réseau LXD existe déjà
  shell: "lxc network list --format csv | grep -w '^{{ network_name }}'"
  register: network_check
  failed_when: false
  changed_when: false

- name: Créer le réseau LXD s'il n'existe pas
  shell: >
    lxc network create {{ network_name }}
    ipv4.address={{ ipv4_address }}
    ipv4.nat={{ ipv4_nat }}
    ipv6.address=none
  when: network_check.rc != 0
  register: network_creation
  changed_when: "'error:' not in network_creation.stderr"

- name: Afficher le statut du réseau
  debug:
    msg: "Le réseau {{ network_name }} existe déjà ou a été créé."
    
- name: Vérifier si la clé SSH existe déjà
  stat:
    path: "{{ ssh_key_path }}"
  register: ssh_key_file
  
- name: Créer clé RSA
  community.crypto.openssh_keypair:
    path: /root/.ssh/k8s_lxd_key
    type: ed25519
    state: present
  when: not ssh_key_file.stat.exists
  
- name: Récupérer la clé publique
  shell: cat {{ ssh_key_path }}.pub
  register: ssh_public_key_result
  changed_when: false
  
- name: Définir la variable de clé publique
  set_fact:
    ssh_public_key: "{{ ssh_public_key_result.stdout }}"



  