---
- name: Display global fact
  ansible.builtin.debug:
    msg: "Global value is: {{ hostvars[groups['masters'][0]]['kubernetes_join_command'] }}"
  when: hostvars[groups['masters'][0]]['kubernetes_join_command'] is defined

- name: Joindre les workers au cluster
  command: "{{ hostvars[groups['masters'][0]]['kubernetes_join_command'] }}"
  when: 
    - inventory_hostname in groups['workers']
  register: join_result
  
- name: Afficher le résultat de la jointure
  debug:
    var: join_result
  when: inventory_hostname in groups['workers']