kubeProxyReplacement: true
l2announcements:
  enabled: true
k8sServiceHost: "10.0.8.151"
k8sServicePort: "6443"
ipam:
  mode: kubernetes
routingMode: native
ipv4NativeRoutingCIDR: "10.0.8.0/16"
autoDirectNodeRoutes: true
enableIPv4Masquerade: true
enableIPMasqAgent: false
tls:
  secretsNamespace:
    create: false
    name: kube-system