# add_hosts_to_group.yaml
- name: "Ajouter les hôtes du cluster '{{ current_cluster }}' au groupe 'target_hosts'"
  ansible.builtin.add_host:
    name: "{{ host_item }}"
    groups: target_hosts
  loop: "{{ groups[current_cluster + '_masters'] | default([]) + groups[current_cluster + '_workers'] | default([]) }}"
  loop_control:
    loop_var: host_item
