---
- name: Vérifier que le script Python existe
  ansible.builtin.stat:
    path: "{{ script_path }}"
  register: script_stat
  failed_when: not script_stat.stat.exists

- name: Exécuter le script Python de mise à jour des kubeconfigs
  ansible.builtin.script:
    cmd: "{{ script_path }} --kubeconfig-dir=../kubeconfig --merge"
  register: script_output
  changed_when: "'Toutes les opérations de mise à jour valides ont été effectuées' in script_output.stdout"
  failed_when: script_output.rc != 0

- name: Afficher la sortie du script
  ansible.builtin.debug:
    var: script_output.stdout_lines
