---
- name: Création de l'infrastructure LXC
  hosts: localhost
  become: yes
  gather_facts: yes  # Active la collecte des facts avant les rôles/tâches
  roles:
    - role: lxc-setup
  
  tasks:
    - name: Transformer la liste cluster_names en chaîne target_cluster
      ansible.builtin.set_fact:
        derived_target_cluster: "{{ cluster_names | join(';') }}"

- name: Configuration du cluster Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Définir target_cluster comme fact
      ansible.builtin.set_fact:
        target_cluster: "{{ hostvars['localhost']['derived_target_cluster'] }}"

    - name: Rafraîchir l'inventaire pour détecter les nouveaux conteneurs
      ansible.builtin.meta: refresh_inventory

- name: Configuration des nodes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Convertir la chaîne de clusters en liste
      ansible.builtin.set_fact:
        target_clusters: "{{ target_cluster.split(';') | map('trim') | list }}"
      when: target_cluster is defined and target_cluster != 'all'

    - name: Définir tous les clusters comme cibles si 'all' est spécifié
      ansible.builtin.set_fact:
        target_clusters: "{{ groups.keys() | select('match', '^((?!masters$|workers$|all$|ungrouped$).)') | list }}"
      when: target_cluster is not defined or target_cluster == 'all'

    - name: Afficher les clusters cibles
      ansible.builtin.debug:
        msg: "Clusters cibles: {{ target_clusters }}"

    - name: Ajouter les hôtes pour chaque cluster cible au groupe 'target_hosts'
      ansible.builtin.include_tasks: add_hosts_to_group.yaml
      loop: "{{ target_clusters }}"
      loop_control:
        loop_var: current_cluster

    - name: Afficher les hôtes cibles pour le ping
      ansible.builtin.debug:
        msg: "Le rôle de ping ciblera les hôtes: {{ groups['target_hosts'] | default([]) }}"
      when: groups['target_hosts'] is defined

- name: Installer les packages common
  hosts: target_hosts
  gather_facts: yes
  become: yes
  roles:
    - role: kubernetes-common

- name: Installer Kubernetes
  hosts: target_hosts
  become: yes
  roles:
    - role: kubernetes-master 

- name: Joindre le worker
  hosts: target_hosts
  become: yes
  roles:
    - role: kubernetes-worker

- name: Récupérer et sauvegarder les fichiers kubeconfig
  hosts: localhost
  gather_facts: no
  vars:
    kubeconfig_dir: "/home/mini/ansible/kubeconfig"
    output_file: "/home/mini/.kube/config" 

  tasks:
    - name: Lire le contenu du fichier kubeconfig
      ansible.builtin.slurp:
        src: /etc/kubernetes/admin.conf
      register: kubeconfig_content
      become: yes
      delegate_to: "{{ groups[item + '_masters'][0] }}"
      when:
        - (item + '_masters') in groups
        - groups[item + '_masters'] | length > 0
      loop: "{{ target_clusters }}"
      loop_control:
        loop_var: item
        
    - name: Afficher le contenu du kubeconfig
      ansible.builtin.debug:
        msg: "{{ kubeconfig_content.results[index].content | b64decode }}"
      loop: "{{ target_clusters }}"
      loop_control:
        loop_var: item
        index_var: index
      when:
        - (item + '_masters') in groups
        - groups[item + '_masters'] | length > 0
        - kubeconfig_content.results[index] is defined
        - kubeconfig_content.results[index].content is defined

    - name: Vérifier et créer le répertoire kubeconfig avec les bonnes permissions
      ansible.builtin.file:
        path: "{{ kubeconfig_dir }}"
        state: directory
        mode: '0750'
        owner: mini
        group: mini
      become: true  

    - name: Créer le répertoire kube
      ansible.builtin.file:
        path: "/home/mini/.kube" 
        state: directory
        mode: '0750' 
        owner: mini
        group: mini
      become: true  

    - name: Créer le fichier kubeconfig en local
      ansible.builtin.copy:
        content: "{{ kubeconfig_content.results[index].content | b64decode }}"
        dest: "{{ kubeconfig_dir }}/config-{{ item }}"
        mode: '0640' 
        owner: "mini"
        group: "mini"
      loop: "{{ target_clusters }}"
      loop_control:
        loop_var: item
        index_var: index
      when:
        - (item + '_masters') in groups
        - groups[item + '_masters'] | length > 0
        - kubeconfig_content.results is defined
        - index < kubeconfig_content.results | length
        - kubeconfig_content.results[index] is defined
        - kubeconfig_content.results[index].content is defined
      become: false  

    - name: Exécuter les tâches de mise à jour du kubeconfig
      include_tasks: run_update_kubeconfig.yaml
      vars:
        script_path: "{{ playbook_dir }}/scripts/update_kubeconfig.py"
    
    - name: Exécuter le script de vérification pour chaque cluster
      ansible.builtin.script:
        cmd: "{{ playbook_dir }}/scripts/check_nodes.py {{ kubeconfig_dir }}/config-{{ item }}"
        executable: /usr/bin/python3
      register: nodes_status
      loop: "{{ cluster_names }}"
      loop_control:
        loop_var: item

    - name: Exécuter le script de renommage pour les clusters prêts
      ansible.builtin.script:
        cmd: "{{ playbook_dir }}/scripts/rename_provisioned_manifest.py {{ item }} {{ playbook_dir }}"
        executable: python3
      loop: "{{ target_clusters }}"
      loop_control:
        loop_var: item
        index_var: index
      when:
        - nodes_status.results is defined
        - index < nodes_status.results | length
        - nodes_status.results[index] is defined
        - nodes_status.results[index].rc == 0
        - "'NotReady' not in nodes_status.results[index].stdout"
      register: rename_script_result
      changed_when: "'Renamed successfully' in rename_script_result.stdout"